name: API Continuos Integration(v16.x)
on: [push]

jobs:
    unit_tests:
        runs-on: ubuntu-latest
        env:
            DATABASE_URI: ${{ secrets.DATABASE_URI }}
            JWT_SECRET: ${{ secrets.JWT_SECRET }}
            TEST_USUARIO_EMAIL: ${{ vars.TEST_USUARIO_EMAIL }}
            TEST_USUARIO_PASSWORD: ${{ vars.TEST_USUARIO_PASSWORD }}
            TEST_USUARIO_ID: ${{ vars.TEST_USUARIO_ID }}
            TEST_USUARIO_JWT: ${{ vars.TEST_USUARIO_JWT }}

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: Install dependencies
              run: npm install

            - name: Run Unit Tests
              run: npm run test:coverage

            - name: Upload coverage reports to Codecov
              uses: codecov/codecov-action@v3
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            - name: Build Dockerfile
              run: docker build .
